server:
  port: 0 # ??? ??(??)? ??

spring:
  application:
    name: user-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true  # eureka ??? ??
    fetch-registry: true  # eureka ????? ??? ???
    service-url:  # eureka ?? ??
      defaultZone: http://localhost:8761/eureka
