server:
  port: 9001

spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true  # eureka ??? ??
    fetch-registry: true  # eureka ????? ??? ???
    service-url:  # eureka ?? ??
      defaultZone: http://localhost:8761/eureka
