server:
  port: 60000 # 랜덤 포트로 실행

spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      name: user-service
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true

#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        prefetch: 5

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      settings:
        web-allow-others: true # 다른 사용자 접근 허용
      path: /h2-console       # H2 Console 접근 URL
      enabled: true           # H2 Console 사용 여부
#  datasource: # config 서버에서 설정을 가져오기 때문에 주석 처리
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username: sa
#    password:

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true  # 유레카 서버에 등록할지 여부
    fetch-registry: true  # 유레카 서버에서 정보를 가져올지 여부
    service-url:  # 유레카 서버 주소
      defaultZone: http://localhost:8761/eureka

# 엑추에이터 설정, actuator/refresh로 접속하면 설정을 다시 불러옴
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"

greeting:
  message: Hello, ${spring.application.name}

logging:
  level:
    org.springframework.cloud: DEBUG
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


#gateway:
#  ip: 10.204.136.204

#token:
#  expiration_time: 86400000
#  secret: user_token_test