spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    # '{cipher}암호화 된 값' 형태로 암호화된 값을 입력
    # 이렇게 입력하면 config 서버에서 암호화된 값이 복호화되어 사용됨
    username: '{cipher}ee1ba6a4ce7839365a01adc23ee0f2652e06c4df2aee72b51f74cde0dac1cfc0'
    password: