server:
  port: 8888

spring:
  #  profiles:
  #    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C://work//git-local-repo
        git: #default uri? ????? ?? ??? ??
          uri: https://github.com/ShimFFF/Spring-MSA-Study-config
          default-label: main
        #          username: <github-id>
        #          password: <gihub-accessToken>
#        bootstrap: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, busrefresh, refresh, metrics